# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/soc_pins.xdc

# Block Designs: bd/microblaze_bd/microblaze_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_bd || ORIG_REF_NAME==microblaze_bd} -quiet] -quiet

# IP: bd/microblaze_bd/ip/microblaze_bd_microblaze_0_0/microblaze_bd_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_bd_microblaze_0_0 || ORIG_REF_NAME==microblaze_bd_microblaze_0_0} -quiet] -quiet

# IP: bd/microblaze_bd/ip/microblaze_bd_dlmb_v10_0/microblaze_bd_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_bd_dlmb_v10_0 || ORIG_REF_NAME==microblaze_bd_dlmb_v10_0} -quiet] -quiet

# IP: bd/microblaze_bd/ip/microblaze_bd_ilmb_v10_0/microblaze_bd_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_bd_ilmb_v10_0 || ORIG_REF_NAME==microblaze_bd_ilmb_v10_0} -quiet] -quiet

# IP: bd/microblaze_bd/ip/microblaze_bd_dlmb_bram_if_cntlr_0/microblaze_bd_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_bd_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblaze_bd_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microblaze_bd/ip/microblaze_bd_ilmb_bram_if_cntlr_0/microblaze_bd_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_bd_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblaze_bd_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microblaze_bd/ip/microblaze_bd_lmb_bram_0/microblaze_bd_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_bd_lmb_bram_0 || ORIG_REF_NAME==microblaze_bd_lmb_bram_0} -quiet] -quiet

# IP: bd/microblaze_bd/ip/microblaze_bd_mdm_1_0/microblaze_bd_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_bd_mdm_1_0 || ORIG_REF_NAME==microblaze_bd_mdm_1_0} -quiet] -quiet

# IP: bd/microblaze_bd/ip/microblaze_bd_clk_wiz_1_0/microblaze_bd_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_bd_clk_wiz_1_0 || ORIG_REF_NAME==microblaze_bd_clk_wiz_1_0} -quiet] -quiet

# IP: bd/microblaze_bd/ip/microblaze_bd_rst_clk_wiz_1_100M_0/microblaze_bd_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_bd_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==microblaze_bd_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/microblaze_bd/ip/microblaze_bd_axi_uartlite_0_0/microblaze_bd_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_bd_axi_uartlite_0_0 || ORIG_REF_NAME==microblaze_bd_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/microblaze_bd/ip/microblaze_bd_axi_gpio_0_0/microblaze_bd_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_bd_axi_gpio_0_0 || ORIG_REF_NAME==microblaze_bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/microblaze_bd/ip/microblaze_bd_xbar_0/microblaze_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_bd_xbar_0 || ORIG_REF_NAME==microblaze_bd_xbar_0} -quiet] -quiet

# IP: bd/microblaze_bd/ip/microblaze_bd_microblaze_0_axi_periph_0/microblaze_bd_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_bd_microblaze_0_axi_periph_0 || ORIG_REF_NAME==microblaze_bd_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/microblaze_bd/ip/microblaze_bd_axi_uartlite_1_0/microblaze_bd_axi_uartlite_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_bd_axi_uartlite_1_0 || ORIG_REF_NAME==microblaze_bd_axi_uartlite_1_0} -quiet] -quiet

# XDC: bd/microblaze_bd/microblaze_bd_ooc.xdc
