# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dorfell/Documents/Vitis_2019.2/socs_design/02_microblaze_axi/02_microblaze_axi.srcs/sources_1/bd/microblaze_bd/ip/microblaze_bd_lmb_bram_0/microblaze_bd_lmb_bram_0.xci
# IP: The module: 'microblaze_bd_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dorfell/Documents/Vitis_2019.2/socs_design/02_microblaze_axi/02_microblaze_axi.srcs/sources_1/bd/microblaze_bd/ip/microblaze_bd_lmb_bram_0/microblaze_bd_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_bd_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/dorfell/Documents/Vitis_2019.2/socs_design/02_microblaze_axi/02_microblaze_axi.srcs/sources_1/bd/microblaze_bd/ip/microblaze_bd_lmb_bram_0/microblaze_bd_lmb_bram_0.xci
# IP: The module: 'microblaze_bd_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dorfell/Documents/Vitis_2019.2/socs_design/02_microblaze_axi/02_microblaze_axi.srcs/sources_1/bd/microblaze_bd/ip/microblaze_bd_lmb_bram_0/microblaze_bd_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_bd_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
